AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Workout API - Serverless backend for managing CrossFit workouts, results, and PRs

# Global configuration for all Lambda functions
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        TABLE_NAME: !Ref WorkoutTable
        NODE_ENV: production
        LOG_LEVEL: info

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - production
    Description: Deployment environment

Resources:
  # DynamoDB Table - Single Table Design
  WorkoutTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'workout-table-${Environment}'
      BillingMode: PAY_PER_REQUEST # On-demand pricing (no capacity planning needed)
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref "Environment"
        - Key: Application
          Value: WorkoutAPI

  # API Gateway
  WorkoutApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'workout-api-${Environment}'
      StageName: !Ref Environment
      Cors:
        AllowMethods: '''GET,POST,PUT,DELETE,OPTIONS'''
        AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
        AllowOrigin: '''*'''
      Auth:
        ApiKeyRequired: false # For now, no API key (add later for production)
      TracingEnabled: true
  # Lambda Functions will be added here in next sprints
  # Example:
  # CreateWODFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: dist/
  #     Handler: presentation/handlers/CreateWODHandler.handler
  #     Events:
  #       CreateWOD:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref WorkoutApi
  #           Path: /wods
  #           Method: POST

Outputs:
  WorkoutApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${WorkoutApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'

  WorkoutTableName:
    Description: DynamoDB table name
    Value: !Ref WorkoutTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'

  WorkoutTableArn:
    Description: DynamoDB table ARN
    Value: !GetAtt WorkoutTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'